trigger:
  branches:
    include: [main]
  paths:
    include:
      - solutions/admin/*

stages:
  - template: ../templates/build.yml
    parameters:
      solutionName: admin
  - template: ../templates/deploy.yml
    parameters:
      solutionName: admin
      environment: Prod
