parameters:
  solutionName: ""

stages:
  - stage: build_${{ parameters.solutionName }}
    jobs:
      - job: build_${{ parameters.solutionName }}
        displayName: Build ${{ parameters.solutionName }}
        pool:
          vmImage: ubuntu-latest
        steps:
          # Build .NET
          # Build PCF
          # Transpile / bundle TS/JS
          - pwsh: |
              ./pwsh/Compress-Solution.ps1 `
                -Name ${{ parameters.solutionName }}
            displayName: Pack Solution
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: solution-artifact
      - job: pack_pwsh
        displayName: Pack pwsh
        pool:
          vmImage: ubuntu-latest
        steps:
          - publish: pwsh
            artifact: pwsh
