parameters:
  solutionName: ""
  environment: ""

stages:
  - stage: ${{ parameters.environment }}
    dependsOn: build_${{ parameters.solutionName }}
    jobs:
    - deployment: Deploy_PowerPlatform_Solution
      displayName: Deploy Power Platform Solution (${{ parameters.solutionName }})
      pool:
        vmImage: ubuntu-latest
      environment: ${{ parameters.environment }}
      variables:
        - group: Credentials
        - group: ${{ parameters.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
              - pwsh: |
                  ./pwsh/Import-Solution.ps1 `
                    -Name ${{ parameters.solutionName }} `
                    -Url $(Url) `
                    -ClientId $(ClientId) `
                    -ClientSecret $(ClientSecret) `
                    -TenantId $(TenantId)
                displayName: Import ${{ parameters.solutionName }}
