parameters:
  solutionName: ""
  packageType: "Both"
  clientId: ""
  clientSecret: ""
  tenantId: ""
  url: ""

jobs:
  - job: Export_${{ parameters.solutionName }}_as_${{ parameters.packageType }}
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        persistCredentials: true
      - pwsh: |
          git checkout ("$(Build.SourceBranch)" -replace "^refs/heads/", "")
          git config user.name "Automated Pipeline Commit on behalf of $(Build.QueuedBy)"
          git config user.email "PPALM-ALM-Build-Account"
        displayName: "Checkout branch and config user"
      - pwsh: |
          ./pwsh/Export-UnpackSolution.ps1 `
            -Name ${{ parameters.solutionName }} `
            -PackageType ${{ parameters.packageType }} `
            -Url ${{ parameters.url }} `
            -ClientId ${{ parameters.clientId }} `
            -ClientSecret ${{ parameters.clientSecret }} `
            -TenantId ${{ parameters.tenantId }}
        displayName: Export / Unpack Solution
      - script: |
          git add .
          git commit -m "Automated commit of ${{ parameters.SolutionName }} solution from ${{ parameters.targetEnvironment }} of type Both"
          git push
