name: Install pac-wrap

on:
  push:

jobs:
  install-pac-wrap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pac-wrap
        run: ./pwsh/Install-PacWrap.ps1
        shell: pwsh
      - run: pac-wrap help
